### ISSUE TITLE
Crash à l'enregistrement.

### ISSUE THREAD

**Issue by michgauz** [owma/AndroidApplication#1]
Lorsque j'essaye de m'enregistrer, ça crash :(

**Comment by spikeuillaume77** [comment]
Bonjour,

Le projet étant abandonné, il n'y a plus aucun serveurs donc plus aucune API permettant la connection sur l'application Android.

Merci toute fois pour l'interêt porté à OWMA.
Cordialement.

L'équipe OWMA.
